# Generated by Django 5.1.5 on 2025-03-19 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicetype',
            options={'ordering': ['category', 'name'], 'verbose_name': 'Услуга', 'verbose_name_plural': 'Услуги'},
        ),
        migrations.AddField(
            model_name='servicetype',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='services/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='servicetype',
            name='category',
            field=models.CharField(choices=[('Диагностика', 'Диагностика'), ('Ремонт', 'Ремонт'), ('ТО', 'ТО')], max_length=50, verbose_name='Категория'),
        ),
    ]
