# Generated by Django 5.1.5 on 2025-04-28 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="specialoffer",
            name="price",
        ),
        migrations.AddField(
            model_name="specialoffer",
            name="discount_percent",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Скидка (%)"
            ),
        ),
        migrations.AlterField(
            model_name="servicetype",
            name="price",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, verbose_name="Цена"
            ),
        ),
    ]
