# Generated by Django 5.1.5 on 2025-03-19 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_servicetype_options_servicetype_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(blank=True, max_length=18, null=True, verbose_name='Телефон'),
        ),
    ]
