# Generated by Django 5.1.5 on 2025-03-30 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('client', 'Клиент'), ('support', 'Поддержка')], default='client', max_length=20, verbose_name='Роль'),
        ),
    ]
