# Generated by Django 5.1.5 on 2025-04-09 16:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_profile_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='appointment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='review', to='app.appointment', verbose_name='Запись на приём'),
        ),
    ]
