# Generated by Django 5.1.5 on 2025-04-09 18:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_review_appointment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='service_record',
        ),
        migrations.AlterField(
            model_name='review',
            name='appointment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='app.appointment', verbose_name='Запись на приём'),
        ),
    ]
